#!/usr/bin/env python3
"""
Generate state/roadmap.md from state/roadmap.yaml

This script ensures roadmap.md is always synchronized with the machine-readable
YAML SSOT. DO NOT EDIT roadmap.md DIRECTLY - edit roadmap.yaml instead.

Usage:
    python scripts/generate_roadmap_md.py
"""

import yaml
from pathlib import Path
from datetime import datetime

def load_roadmap_yaml(yaml_path: Path) -> dict:
    """Load and parse roadmap.yaml"""
    with open(yaml_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def status_emoji(status: str) -> str:
    """Convert status to emoji"""
    emoji_map = {
        'COMPLETED': '✅',
        'IN_PROGRESS': '🔄',
        'READY': '🔲',
        'BLOCKED': '⏸️',
        'PLANNED': '📋',
        'DEPRECATED': '⛔',
        'UNKNOWN': '❓'
    }
    return emoji_map.get(status, '❓')

def format_milestone_header(milestone: dict, tasks_map: dict) -> str:
    """Format milestone as markdown header with task table"""
    status = status_emoji(milestone['status'])
    name = milestone['name']
    summary = milestone['summary']

    md = [f"## {name}\n"]
    md.append(f"**Status**: {milestone['status']} {status}  ")
    md.append(f"**Summary**: {summary}\n")

    if milestone.get('outcome'):
        md.append(f"**Outcome**: {milestone['outcome']}\n")

    # Build task table
    milestone_tasks = [tasks_map[tid] for tid in milestone.get('tasks', []) if tid in tasks_map]

    if milestone_tasks:
        md.append("| ID | Feature | Owner | Status | Outcome |")
        md.append("|---|---|---|---|---|")

        for task in milestone_tasks:
            task_id = task['id'].upper().replace('-', '-T').split('-T')[1] if '-t' in task['id'] else task['id']
            name = task['name'].split(': ', 1)[1] if ': ' in task['name'] else task['name']
            owner_agent = task['owners'][0]['agent'] if task.get('owners') else 'Unassigned'
            status_str = f"{task['status']} {status_emoji(task['status'])}"

            outputs = ', '.join(task.get('outputs', [])[:2])  # First 2 outputs
            if len(task.get('outputs', [])) > 2:
                outputs += ', ...'

            md.append(f"| {task_id} | {name} | {owner_agent} | {status_str} | {outputs} |")

    md.append("\n---\n")
    return '\n'.join(md)

def generate_roadmap_md(roadmap_data: dict) -> str:
    """Generate complete roadmap.md content"""
    metadata = roadmap_data.get('metadata', {})
    milestones = roadmap_data.get('milestones', [])
    tasks = roadmap_data.get('tasks', [])

    # Build task lookup map
    tasks_map = {task['id']: task for task in tasks}

    # Header
    md = ["# TR4D3RZ — ROADMAP\n"]
    md.append(f"**Generated from**: `state/roadmap.yaml` (SSOT)  ")
    md.append(f"**Schema version**: {roadmap_data.get('schema_version', 'unknown')}  ")
    md.append(f"**Last updated**: {metadata.get('last_updated', 'unknown')}  ")
    md.append(f"**Current Milestone**: {metadata.get('current_milestone', 'unknown').upper().replace('-', ' ').title()}  \n")

    md.append("⚠️ **DO NOT EDIT THIS FILE DIRECTLY**  ")
    md.append("This file is auto-generated from `state/roadmap.yaml`. To update the roadmap, ")
    md.append("edit the YAML file and run `python scripts/generate_roadmap_md.py`.\n")
    md.append("---\n")

    # Milestones
    current_milestone_id = metadata.get('current_milestone')

    # Current milestone first
    current_milestone = next((m for m in milestones if m['id'] == current_milestone_id), None)
    if current_milestone:
        md.append(format_milestone_header(current_milestone, tasks_map))

    # Other milestones
    for milestone in milestones:
        if milestone['id'] != current_milestone_id:
            md.append(format_milestone_header(milestone, tasks_map))

    # Footer
    md.append("---\n")
    md.append(f"*Auto-generated from `state/roadmap.yaml` on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC*  ")
    md.append("*Edit the YAML source, not this file*\n")

    return '\n'.join(md)

def main():
    """Main entry point"""
    import sys
    # Fix Windows console encoding
    if sys.platform == 'win32':
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

    repo_root = Path(__file__).parent.parent
    yaml_path = repo_root / 'state' / 'roadmap.yaml'
    md_path = repo_root / 'state' / 'roadmap.md'

    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found")
        return 1

    print(f"Loading {yaml_path}...")
    roadmap_data = load_roadmap_yaml(yaml_path)

    print(f"Generating roadmap.md...")
    md_content = generate_roadmap_md(roadmap_data)

    print(f"Writing {md_path}...")
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_content)

    print(f"[OK] Generated {md_path} ({len(md_content)} chars)")
    print(f"   Milestones: {len(roadmap_data.get('milestones', []))}")
    print(f"   Tasks: {len(roadmap_data.get('tasks', []))}")

    return 0

if __name__ == '__main__':
    exit(main())
